spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/chadet_auth
    username: chadet_user
    password: chadet_password
    driver-class-name: org.postgresql.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:chadet}
    password: ${RABBITMQ_PASSWORD:chadet_password}
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 30
    connect-retries-interval: 5
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

chadet:
  jwt:
    private-key: LS0tLS1CRUdJTiBQUklWQVRFIEtFWS0tLS0tCk1JSUV2Z0lCQURBTkJna3Foa2lHOXcwQkFRRUZBQVNDQktnd2dnU2tBZ0VBQW9JQkFRQ3p1SUFCd3cxcDJuaGsKb1JzYUl0YzV5Q1ZZVEJhckFUcEo3clc3ZlpyUUxycFFlb1IySmNQNnRmeHpBc2NwNFFPSlMxQjVCTWQvcHFPUApoYTZ5WlZtY2ZLbDVtQkljT3RkMFljZ3FDQkdmdUo2QXE5WTFnb0phSU4wbVBZNlRqd0M3dXJleGVPUWMyWWFkCnNkMmVZZ0dsUm1XcVJvd0ZTMHgxTWJheHRlZmlEQXlEcTQ0MHJYc3FDZ3NvM2tTaGRyTkVPbTJsWE01V01NS0oKL1diWnI0a2dTS0IyNlVDcEViS21ZOWdZM205aHRwa0dVZGJzVlFha0pPL0k0dVRlKzhmR0ZIaXB2ZXVQY3QwNAp1TlYyeXlsL2d1TGNCQjZmMWcvNkZPZDI2UGluaW1zc1h6bklqZFRoZzBxbkdXcGdXZjlYU0VBaE1nakxuUjVnCkh1SlMyRXV6QWdNQkFBRUNnZ0VBQ0VBSmZFczRjK29JQ2RLTmZITXAveWlOY2xLMzNhekdRTHVaRXh6T2ZRMFEKRjM2d1V2NGowNEFFTVVGbzVDYkVzMHBHVE8vbnVwZnJQVHp0U3BvMWRXWVJuNWZZQ1B5NGhFcXkxaDhkcy8vVgpJdUlBaU45UFhaVFJvaDVFUzhqT1IwL29lOWlwWEJ1dVB0SDU4dm5ieW5zRFVzQS9VRVRuSXlBZm0yUFcyNzBPCit2MmZVRUxwME1IVkVtR2Q5MkJoRWxQb1hYV2hjeEpQM1ZOclRvYzZid0RxMEI2OUNHNytDTXBPRVFKY05TengKQ3pTRFBCQzBYUUZFQTh0N29ZRG5xcnFmMFVYK0lSMmJBdmJRTXZnbDJZSUFEa3E3VXRlOFZaL0QxVjdUS2grSgpCVGlmU3AvamhCb29ncVM2QkJpMmtWbVJ2ZVAzT2hGdHRBOHl3RHJzUVFLQmdRRDJDalpNK1NFQ3NyN2x2dDNuCndVcXVwRzlGL2lrSS9Rbm0xQzNNd0Jad1JUNjdqZ3pqdVViV3UyUXNGQ0hhUGp0WVJlakg5M3Mxc2lCdjBEZ24KUGkybjBIUlltNGZja3o3TmY5R1Zid2pkWWNjY2VhazRhMHVoOTYwYUY3MG45SjVBM1Z1eDkvLzNkUm1oMlZLcQpLSDhaY3FlTlBaN2RyTDBnbkxqbG8zRmVRUUtCZ1FDNi93Qmx0RnhDWUJma2cxZkQ5eWoxaTVYL2xnT1M2ZlRmClN0UVp2aW5Ybk5sU2RuTXREc09MT2ZwZHFoTzl1WHlDdW1nVndkZmRlb2wvVS9pYlFJVXZzSzBPSnYwNXBsTkgKaVcvUExJZ205Y3VqcEVidmJuRGpFTkgxV29Vb3V6TzNNeGRtQXhWbnFCY1JXME84MzBFcU4zN3pzS3dNUlpRbQpwckFwUEs3VTh3S0JnUUNjQjJQaU1vZE5wNzlLQVYzR2NCMEZYY0EzT2ZRYUFDWThYVWhpTlZyRmZoUkhhdEVmCnhVcDRPTVJRODc5NElNa1B0TjNubWpsbmx2dmRETVhmbFIzczgxUWxNUlRhdkFJeTNpRXlUQVRxSit6V1VRMFEKZTNLdVYxeE9WTW1mUWhEdC83TDd6Tk5sd2J3c21KNUV6SU8xeHJFYzcvd0VobHcyQjAxMlM4MUVRUUtCZ1FDdgprd3B1ZEFCRUdqR1V6M1d5ZS9pclJGcWNWZUFaS3k1T0VkWkFMWHJnQlZkUHhBTzBoSzQ1cFVCY2ZYcDNveGN6Ckw0N1hEdUIrQmJYZ0pabkJPNzFSMzlNOC9JSzZoRjZoUm53Q3k4OHl0WXAwcGFRczMwZURDNkgzZXZ5WUY5MGcKNEFuU01JY0NncUxXR3hqbzE3NDV3MDJoeFhwbE0xYzlTemtRSHZnUTNRS0JnQ2UxNFNldUJaN0FuM21JMUl4SQpoZVhXV3dwR1ZxampvekdxZUNlcGVPcHNqb1FRUlVBUjhrTG9KSkJqdkYzOVdCVXRDbUZJNlRlanA2V2ErLzVyCnpUN1E3RzFyTmI1Qm94Rkc4dkxpUUdFREdsc1BYKzRQRHRtdVBoWGNGSENraFNpRjdEVjRvc0pDclRRSzQzeWcKYUphR1lhQmFYa0FVNWF4TGhRblVOeklMCi0tLS0tRU5EIFBSSVZBVEUgS0VZLS0tLS0K
    public-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzN2lBQWNNTmFkcDRaS0ViR2lMWApPY2dsV0V3V3F3RTZTZTYxdTMyYTBDNjZVSHFFZGlYRCtyWDhjd0xIS2VFRGlVdFFlUVRIZjZhamo0V3VzbVZaCm5IeXBlWmdTSERyWGRHSElLZ2dSbjdpZWdLdldOWUtDV2lEZEpqMk9rNDhBdTdxM3NYamtITm1HbmJIZG5tSUIKcFVabHFrYU1CVXRNZFRHMnNiWG40Z3dNZzZ1T05LMTdLZ29MS041RW9YYXpSRHB0cFZ6T1ZqRENtZjFtMmErSgpJRWlnZHVsQXFSR3lwbVBZR041dlliYVpCbEhXN0ZVR3BDVHZ5T0xrM3Z2SHhoUjRxYjNyajNMZE9MalZkc3NwCmY0TGkzQVFlbjlZUCtoVG5kdWo0cDRwckxGODV5STNVNFlOS3B4bHFZRm4vVjBoQUlUSUl5NTBlWUI3aVV0aEwKc3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==
  
server:
  port: 8081

logging:
  level:
    com.tienvm.auth: INFO