spring:
  application:
    name: trade-service
  datasource:
    url: jdbc:postgresql://localhost:5433/chadet_trade
    username: chadet_trade
    password: chadet_password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false
  flyway:
    enabled: true
    locations: classpath:db/migration
    baseline-on-migrate: true
    connect-retries: 30
    connect-retries-interval: 5

server:
  port: 8083
