spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      server:
        webflux:
          default-filters:
            - DedupeResponseHeader=Access-Control-Allow-Origin Access-Control-Allow-Credentials, RETAIN_UNIQUE
          routes:
            - id: user-service
              uri: http://localhost:8081
              predicates:
                - Path=/api/auth/**,/api/users/**,/api/user/**
            - id: chat-service
              uri: http://localhost:8082
              predicates:
                - Path=/api/conversations/**,/api/messages/**,/ws/**
            - id: trade-service
              uri: http://localhost:8083
              predicates:
                - Path=/api/trades/**,/api/wallet/**,/trade-ws/**
            - id: auth-docs
              uri: http://localhost:8081
              predicates:
                - Path=/auth/docs, /auth/docs/**, /auth/scalar, /auth/scalar/**, /auth/v3/api-docs, /auth/v3/api-docs/**, /auth/scalar.html, /auth/api-docs, /auth/api-docs/**
              filters:
                - RewritePath=/auth/(?<segment>.*), /${segment}
            - id: chat-docs
              uri: http://localhost:8082
              predicates:
                - Path=/chat/docs, /chat/docs/**, /chat/scalar, /chat/scalar/**, /chat/v3/api-docs, /chat/v3/api-docs/**, /chat/scalar.html
              filters:
                - RewritePath=/chat/(?<segment>.*), /${segment}
            - id: trade-docs
              uri: http://localhost:8083
              predicates:
                - Path=/trade/docs, /trade/docs/**, /trade/scalar, /trade/scalar/**, /trade/v3/api-docs, /trade/v3/api-docs/**, /trade/scalar.html
              filters:
                - RewritePath=/trade/(?<segment>.*), /${segment}

chadet:
  jwt:
    public-key: LS0tLS1CRUdJTiBQVUJMSUMgS0VZLS0tLS0KTUlJQklqQU5CZ2txaGtpRzl3MEJBUUVGQUFPQ0FROEFNSUlCQ2dLQ0FRRUFzN2lBQWNNTmFkcDRaS0ViR2lMWApPY2dsV0V3V3F3RTZTZTYxdTMyYTBDNjZVSHFFZGlYRCtyWDhjd0xIS2VFRGlVdFFlUVRIZjZhamo0V3VzbVZaCm5IeXBlWmdTSERyWGRHSElLZ2dSbjdpZWdLdldOWUtDV2lEZEpqMk9rNDhBdTdxM3NYamtITm1HbmJIZG5tSUIKcFVabHFrYU1CVXRNZFRHMnNiWG40Z3dNZzZ1T05LMTdLZ29MS041RW9YYXpSRHB0cFZ6T1ZqRENtZjFtMmErSgpJRWlnZHVsQXFSR3lwbVBZR041dlliYVpCbEhXN0ZVR3BDVHZ5T0xrM3Z2SHhoUjRxYjNyajNMZE9MalZkc3NwCmY0TGkzQVFlbjlZUCtoVG5kdWo0cDRwckxGODV5STNVNFlOS3B4bHFZRm4vVjBoQUlUSUl5NTBlWUI3aVV0aEwKc3dJREFRQUIKLS0tLS1FTkQgUFVCTElDIEtFWS0tLS0tCg==

server:
  port: 8080

logging:
  level:
    com.tienvm.gateway: INFO