services:
  postgres:
    image: docker.io/library/postgres:17-alpine
    environment:
      - POSTGRES_DB=chadet_auth
      - POSTGRES_USER=chadet_user
      - POSTGRES_PASSWORD=chadet_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: